"""
Phase 6 Stage 6.4 — AI Website Code Generation Schemas.

Defines Pydantic models for:
- GeneratedWebsiteFile & GeneratedWebsiteProject (structured representation of generated codebase)
- Request & Response payloads for Code Generation API
- Manifest & File Inspector models
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional
import uuid

from pydantic import BaseModel, ConfigDict, Field, field_validator


class GeneratedWebsiteFile(BaseModel):
    """Represents a single generated source code or asset file."""
    model_config = ConfigDict(extra="ignore")

    path: str = Field(..., description="Normalized relative path within the generated Next.js project")
    content: str = Field(..., description="Raw text content of the file")
    file_type: str = Field(..., description="File classification (tsx, ts, css, json, markdown, mjs, svg)")
    checksum: str = Field(..., description="SHA-256 hex digest of file content")
    size_bytes: int = Field(..., ge=0, description="Size of file in bytes")

    @field_validator("path")
    @classmethod
    def validate_relative_path(cls, v: str) -> str:
        clean = v.strip().replace("\\", "/")
        if clean.startswith("/"):
            clean = clean.lstrip("/")
        if ".." in clean.split("/"):
            raise ValueError(f"Path traversal detected in file path: {v}")
        if ":" in clean:
            raise ValueError(f"Windows drive prefix detected in file path: {v}")
        if "\x00" in clean:
            raise ValueError("Null byte detected in file path")
        return clean


class GeneratedWebsiteProject(BaseModel):
    """Complete structured Next.js + React project generated by the code generation engine."""
    model_config = ConfigDict(extra="ignore")

    framework: str = Field(default="nextjs", description="Target framework")
    language: str = Field(default="typescript", description="Language used")
    package_manager: str = Field(default="npm", description="Package manager")
    files: List[GeneratedWebsiteFile] = Field(default_factory=list, description="All project files")
    entrypoints: List[str] = Field(default_factory=list, description="Primary entrypoint paths")
    routes: List[str] = Field(default_factory=list, description="Declared route paths")
    components: List[str] = Field(default_factory=list, description="Reusable component names")
    assets: List[str] = Field(default_factory=list, description="Asset paths")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Build & generation metadata")


class WebsiteCodeGenerationCreateRequest(BaseModel):
    """Request payload to initiate code generation."""
    model_config = ConfigDict(extra="ignore")

    design_blueprint_id: Optional[uuid.UUID] = Field(
        default=None,
        description="Optional explicit blueprint ID. If omitted, uses latest completed blueprint.",
    )


class WebsiteCodeGenerationCancelRequest(BaseModel):
    """Request payload to cancel an active code generation."""
    model_config = ConfigDict(extra="ignore")

    reason: Optional[str] = Field(default=None, description="Optional cancellation rationale")


class WebsiteCodeGenerationResponse(BaseModel):
    """Summary item for a code generation."""
    model_config = ConfigDict(from_attributes=True, extra="ignore")

    id: uuid.UUID
    project_id: uuid.UUID
    build_session_id: uuid.UUID
    website_generation_id: uuid.UUID
    design_blueprint_id: uuid.UUID
    approved_prd_id: uuid.UUID
    owner_id: str
    prd_version: int
    code_generation_version: int
    status: str
    provider: str
    model: str
    source_checksum: Optional[str] = None
    file_count: int = 0
    source_artifact_id: Optional[uuid.UUID] = None
    error_code: Optional[str] = None
    error_message: Optional[str] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    failed_at: Optional[datetime] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime
    updated_at: datetime


class WebsiteCodeGenerationDetailResponse(WebsiteCodeGenerationResponse):
    """Detailed view of a code generation with manifest summary."""
    project_name: Optional[str] = None
    project_slug: Optional[str] = None
    manifest: Optional[Dict[str, Any]] = None
    files_summary: Optional[List[Dict[str, Any]]] = None


class WebsiteCodeGenerationListResponse(BaseModel):
    """Paginated or complete list of code generations for a build session."""
    model_config = ConfigDict(extra="ignore")

    items: List[WebsiteCodeGenerationResponse]
    total: int
    completed_count: int
    failed_count: int
    active_count: int


class WebsiteCodeGenerationManifestResponse(BaseModel):
    """Structured file manifest response for a completed code generation."""
    model_config = ConfigDict(extra="ignore")

    generation_id: uuid.UUID
    version: int
    framework: str
    language: str
    source_checksum: str
    file_count: int
    entrypoints: List[str]
    routes: List[str]
    components: List[str]
    files: List[Dict[str, Any]]  # [{path, size_bytes, checksum, file_type}]


class WebsiteCodeGenerationFilesResponse(BaseModel):
    """File content or list of files response."""
    model_config = ConfigDict(extra="ignore")

    generation_id: uuid.UUID
    files: List[GeneratedWebsiteFile]
